// Module F — shared AI procurement cases walking the responsibility cascade.
// Mounted inside routes/ai.js, so everything lives under /api/ai/*.
//
// The access rule, enforced here rather than in the browser: a case is held by one of the
// two agencies at a time, and only a signed-in position belonging to that agency may raise
// the next note. Anyone signed in may read the file. That is the sheet's row 23,
// "Note Can only be Generated by", turned into an authorisation check.

import { Router } from 'express';
import * as access from '../ai/access.js';
import * as store from '../ai/caseStore.js';
import * as graph from '../ai/cascadeGraph.js';
import * as loadInputs from '../ai/loadInputs.js';
import * as slm from '../ai/slm.js';

const router = Router();
const fail = (res, code, error, extra = {}) => res.status(code).json({ error, ...extra });

// What this position is, and what it may do at all. The screen uses this to decide
// whether to offer a "new case" button before any case exists.
router.get('/me', (req, res) => {
  const role = req.user?.role;
  res.json({
    user: { id: req.user?.id, name: req.user?.name, role },
    roleLabel: access.ROLE_LABEL[role] ?? role,
    agencies: access.agenciesFor(role),
    readOnly: access.isReadOnly(role),
    canCreate: access.agenciesFor(role).includes(access.INDENTING),
    // Stated plainly: sampleData never maps job titles onto the sheet's two agencies.
    note: 'The responsibility sheet names only two actors, Indenting and Tendering, and '
      + 'never maps HAL job titles onto them. This mapping is an assumption — see '
      + 'server/ai/access.js.',
    mapping: access.ROLE_AGENCIES
  });
});

// Is the language model reachable? The screen shows this before anyone tries to generate,
// because a note raised without it comes back with the section marked, not silently empty.
router.get('/slm', async (_req, res) => res.json(await slm.health()));

// The cases available to seed a file from (real sampleData case, or the fabricated one).
router.get('/cases/sources', (_req, res) => res.json({ sources: loadInputs.availableCases() }));

// Every case, each flagged with whether it is waiting on this position.
router.get('/cases', (req, res) => {
  const cases = store.listCases(req.user);
  res.json({
    cases,
    mine: cases.filter((c) => c.withMe).length,
    open: cases.filter((c) => c.status === 'open').length,
    agencies: access.agenciesFor(req.user?.role)
  });
});

// Open a new file. A case starts with the indent, so this is the Indenting agency's move.
router.post('/cases', (req, res) => {
  if (!access.agenciesFor(req.user?.role).includes(access.INDENTING)) {
    return fail(res, 403,
      `A procurement case starts with the indent, which is the Indenting Agency's move. `
      + `Your position (${access.ROLE_LABEL[req.user?.role] ?? req.user?.role}) acts for `
      + `${access.agenciesFor(req.user?.role).join(' / ') || 'no agency'}.`);
  }
  const { caseRef, title, sourceCase } = req.body ?? {};
  try {
    res.status(201).json({ case: store.createCase({ caseRef, title, sourceCase, user: req.user }) });
  } catch (e) {
    fail(res, 422, String(e?.message ?? e));
  }
});

router.get('/cases/:id', (req, res) => {
  const c = store.loadCase(Number(req.params.id), req.user);
  return c ? res.json({ case: c }) : fail(res, 404, 'No such case');
});

// The editable form for one note — pre-filled, with the block-3 prerequisite warnings.
router.get('/cases/:id/form/:noteId', (req, res) => {
  const out = store.noteForm(Number(req.params.id), req.params.noteId);
  return out.ok ? res.json(out) : fail(res, 422, out.error);
});

// Raise a note. Generation is real: annexures in code, prose from the model, the prior
// note carried forward. 428 means an advisory rule points elsewhere — resend with
// override: true to proceed, and the override is recorded on the note.
router.post('/cases/:id/notes', async (req, res) => {
  const { noteId, fields, override } = req.body ?? {};
  if (!noteId) return fail(res, 422, 'noteId is required');
  const out = await store.raiseNote(Number(req.params.id), noteId, {
    fields: fields ?? {}, override: Boolean(override), user: req.user
  });
  if (!out.ok) {
    return fail(res, out.code ?? 422, out.error,
      out.needsOverride ? { needsOverride: true, advised: out.advised } : {});
  }
  res.json({
    skipped: Boolean(out.skipped),
    branch: out.branch ?? null,
    result: out.result ?? null,
    handoverNeeded: out.handoverNeeded ?? null,
    case: out.kase
  });
});

// Take the file across to your agency.
router.post('/cases/:id/handover', (req, res) => {
  const out = store.handOver(Number(req.params.id), {
    user: req.user, toAgency: req.body?.toAgency ?? null
  });
  return out.ok ? res.json({ case: out.kase }) : fail(res, out.code ?? 422, out.error);
});

// Block 1 of the sheet — the pre-tender input checklist and who owns each line. Shown at
// the provisioning and tender nodes, which the sheet marks as checklist points.
router.get('/checklist-block1', (_req, res) => res.json({ checklist: graph.CHECKLIST }));

export default router;
