// Column configs + shared enums for Module D (contracts) grids. Screens compose DataGrid
// with these — columns are never defined inline in a screen. Contracts carry their own
// FIVE-level classification (incl. Restricted) — separate from noting's four.
import { Link } from 'react-router-dom';
import { formatINR } from '../lib/currency.js';

export const CONTRACT_CLASSIFICATIONS = [
  { id: 'normal', label: 'Normal' },
  { id: 'restricted', label: 'Restricted' },
  { id: 'confidential', label: 'Confidential' },
  { id: 'secret', label: 'Secret' },
  { id: 'top_secret', label: 'Top Secret' }
];
export const contractClsLabel = (id) => CONTRACT_CLASSIFICATIONS.find((c) => c.id === id)?.label || id;

export function ContractClassificationBadge({ value }) {
  return <span className={`tag tag-cls-${value}`}>{contractClsLabel(value)}</span>;
}

export function ContractStatusBadge({ value }) {
  return <span className={`tag tag-ctr-${value}`}>{value === 'finalised' ? 'Finalised' : 'Draft'}</span>;
}

export const REGISTER_COLUMNS = [
  {
    key: 'contract_no',
    label: 'Contract No',
    render: (r) => <Link to={`/contracts/view/${r.id}`}>{r.contract_no}</Link>
  },
  { key: 'created_at', label: 'Generated' },
  { key: 'description', label: 'Description of contract' },
  { key: 'vendor_name', label: 'Supplier' },
  { key: 'type_label', label: 'Type' },
  { key: 'landed_value', label: 'Value', align: 'right', render: (r) => formatINR(r.landed_value) },
  { key: 'validity', label: 'Validity' },
  { key: 'po_no', label: 'PO No' },
  { key: 'tender_no', label: 'Tender No' },
  { key: 'car_no', label: 'CAR' },
  { key: 'classification', label: 'Class.', render: (r) => <ContractClassificationBadge value={r.classification} /> },
  { key: 'status', label: 'Status', render: (r) => <ContractStatusBadge value={r.status} /> },
  { key: 'generated_by_name', label: 'Generated by', render: (r) => `${r.generated_by_name || '—'} (${r.generated_by_pb || '—'})` }
];

// CSV export mirrors the client's full register field list (incl. CFA/DOP, mode, parties).
export const REGISTER_CSV_COLUMNS = [
  { label: 'Contract No', value: (r) => r.contract_no },
  { label: 'Generation date', value: (r) => r.created_at },
  { label: 'Description', value: (r) => r.description },
  { label: 'HAL party', value: (r) => r.hal_division },
  { label: 'Supplier', value: (r) => r.vendor_name },
  { label: 'Supplier GSTIN', value: (r) => r.vendor_gstin },
  { label: 'Supplier address', value: (r) => r.vendor_address },
  { label: 'Supplier contact', value: (r) => r.vendor_contact },
  { label: 'Type of contract', value: (r) => r.type_label },
  { label: 'Currency', value: (r) => r.currency },
  { label: 'Basic value', value: (r) => r.basic_value },
  { label: 'Tax total', value: (r) => r.tax_total },
  { label: 'Contract value (landed)', value: (r) => r.landed_value },
  { label: 'Period from', value: (r) => r.period_from },
  { label: 'Period to', value: (r) => r.period_to },
  { label: 'Validity', value: (r) => r.validity },
  { label: 'CAR No', value: (r) => r.car_no },
  { label: 'Tender No', value: (r) => r.tender_no },
  { label: 'CFA & DOP reference', value: (r) => r.cfa_dop_ref },
  { label: 'Mode of tendering', value: (r) => r.mode_of_tendering },
  { label: 'PO No', value: (r) => r.po_no },
  { label: 'Classification', value: (r) => contractClsLabel(r.classification) },
  { label: 'Status', value: (r) => r.status },
  { label: 'Generated by', value: (r) => r.generated_by_name },
  { label: 'PB No', value: (r) => r.generated_by_pb },
  { label: 'Designation', value: (r) => r.generated_by_desig },
  { label: 'Department', value: (r) => r.generated_by_dept },
  { label: 'Division', value: (r) => r.generated_by_division }
];

export const ITEM_COLUMNS = [
  { key: 'line_no', label: 'Sl.', align: 'right' },
  { key: 'part_no', label: 'Part No' },
  { key: 'description', label: 'Part description' },
  { key: 'hsn', label: 'HSN' },
  { key: 'qty', label: 'Qty', align: 'right' },
  { key: 'uom', label: 'UOM' },
  { key: 'unit_price', label: 'Unit price', align: 'right', render: (r) => formatINR(r.unit_price ?? r.unitPrice) },
  { key: 'gst', label: 'Tax', render: (r) => `${r.gst_type ?? r.gstType} @ ${r.gst_pct ?? r.gstPct}%` },
  { key: 'tax_amount', label: 'Tax amount', align: 'right', render: (r) => formatINR(r.tax_amount ?? r.taxAmount) },
  { key: 'line_total', label: 'Line total', align: 'right', render: (r) => formatINR(r.line_total ?? r.lineTotal) }
];

// Library columns take an onOpen(row) callback so the title cell opens the clause drawer.
export const libraryColumns = (onOpen) => [
  { key: 'matrix_no', label: 'Clause No', align: 'right', render: (r) => r.matrix_no ?? '—' },
  {
    key: 'title',
    label: 'Standard contractual clause',
    render: (r) => (
      <button type="button" className="link-btn" onClick={() => onOpen(r)}>
        {r.title}
      </button>
    )
  },
  { key: 'boilerplate', label: 'Boilerplate', render: (r) => (r.boilerplate ? 'Yes' : 'No') },
  { key: 'version', label: 'Version', align: 'right', render: (r) => `v${r.version}` },
  { key: 'updated_at', label: 'Last amended', render: (r) => r.updated_at || '—' }
];

export const HISTORY_COLUMNS = [
  { key: 'version', label: 'Superseded ver.', align: 'right', render: (r) => `v${r.version}` },
  { key: 'changed_at', label: 'Changed' },
  { key: 'changed_by_name', label: 'Changed by', render: (r) => `${r.changed_by_name || '—'} (${r.changed_by_pb || '—'})` },
  { key: 'change_note', label: 'Change note' },
  { key: 'reference_doc', label: 'Reference doc' }
];

// Matrix grid: one row per clause, one dynamic column per contract type with tone classes.
const cellTone = (v) => (v === 'Y' ? 'mx-y' : v === 'N' ? 'mx-n' : v === 'TBD' ? 'mx-tbd' : 'mx-cond');
export const matrixColumns = (contractTypes) => [
  { key: 'matrix_no', label: 'No', align: 'right' },
  { key: 'title', label: 'Clause' },
  ...contractTypes.map((t) => ({
    key: t.id,
    label: t.label,
    render: (r) => {
      const v = r.cells[t.id];
      if (v == null) return <span className="mx-cell mx-cond">Optional</span>;
      const short = v === 'Y' || v === 'N' || v === 'TBD' ? v : 'Cond.';
      return (
        <span className={`mx-cell ${cellTone(v)}`} title={v}>
          {short}
        </span>
      );
    }
  }))
];
