`"""Responsibility cascade -- a machine-readable copy of

    sampleData/HAL PURCHASE FORMATS dt 22.06.2026/
        Note & Format Generation Stages and responsibility cascadeing.xlsx

That sheet holds three blocks, and only two agencies ever act:

  Block 1 (B5:D25)  "INPUTS FOR TENDER DOCUMENT GENERATION" -- the pre-tender
                    checklist, each line owned by one agency (CHECKLIST below).
  Block 2 (F4:M24)  "TYPE OF NOTES POSSIBLE AFTER TENDER OPENING" -- eight stage
                    columns; each column lists the notes that may be raised at
                    that stage, and row 22-23 ("Note Can only be Generated by")
                    names the single agency allowed to raise them (NODES below).
  Block 3 (F25:H35) "FORMATS POST TENDER OPENING" with RESPONSIBILITY and
                    "Required for" -- POST_TENDER_FORMATS / PREREQ_FORMATS below.

stages.py holds the *note* definitions (fields, annexures, carry-forward); this
module holds only who may act, and what may follow what.
"""

INDENTING = "Indenting"
TENDERING = "Tendering"
AGENCY_LABEL = {INDENTING: "Indenting Agency", TENDERING: "Tendering Agency"}
AGENCIES = [INDENTING, TENDERING]

# -- Block 1 -- inputs for tender document generation -------------------------
# (label, owning agency). Groups mirror the sheet's own sub-headings.
CHECKLIST = [
    ("PROVISIONING NOTE", [
        ("Indentor Checklist  (Tender No. from IFS)", INDENTING),
        ("MPR/CAR/SPR/CPR -- descp, part no, qty, delivery period, type of tendering", INDENTING),
        ("Technical Specs", INDENTING),
        ("Scope of Work", INDENTING),
        ("Proprietary / OEM Service Certificate", INDENTING),
        ("Single Tender / Nomination Certificate", INDENTING),
        ("Commercial Conditions", TENDERING),
    ]),
    ("FORMATS (FOR INDENT)", [
        ("MII -- Make in India purchase preference", TENDERING),
        ("LBS -- land border sharing restriction (GFR 144(ix))", TENDERING),
        ("Non-poaching undertaking", TENDERING),
        ("Non-debarring undertaking", TENDERING),
        ("NDA", TENDERING),
        ("IP -- Integrity Pact", TENDERING),
        ("SD -- Security Deposit BG format", TENDERING),
        ("PBG -- Performance BG format", TENDERING),
    ]),
    ("IFS REFERENCE", [
        ("IFS Tender Enquiry No. -- against Requisition No.", TENDERING),
    ]),
]

# -- Block 3 -- formats generated after tender opening ------------------------
# fid keys into formats.REG, where this pipeline already builds the annexure.
POST_TENDER_FORMATS = [
    ("TEC Report",                    INDENTING, "Price Bid Opening, PNC & Purchase Proposal", "tec_statement"),
    ("Commercial Evaluation Report",  TENDERING, "PNC & Purchase Proposal",                    "commercial_eval"),
    ("Comparative Statement",         TENDERING, "PNC & Purchase Proposal",                    "comparative_statement"),
    ("Price Justification Statement", TENDERING, "PNC & Purchase Proposal",                    "price_justification"),
    ("Agenda of Negotiation",         TENDERING, "PNC Approval & PNC Recommendation",          "pnc_agenda"),
    ("PNC Recommendation",            TENDERING, "Purchase Proposal",                          "pnc_recommendation"),
    ("Purchase Proposal",             TENDERING, "Purchase Order / Contract",                  "purchase_proposal"),
    ("Purchase Order",                TENDERING, "Contract / PO Amendment",                    "purchase_order"),
    ("Contract",                      TENDERING, "PO Amendment",                               "hal_contract"),
    ("Advance Payment Format",        TENDERING, "Advance Payment Note / Purchase Proposal",   "advance_payment"),
]

FORMAT_OWNER = {fid: resp for _, resp, _, fid in POST_TENDER_FORMATS}
FORMAT_TITLE = {fid: name for name, _, _, fid in POST_TENDER_FORMATS}

# Block 3's "Required for" column, inverted: note -> (format, always-required?).
# A missing one is warned about, never blocked -- a format owned by the other agency
# is exactly the hand-over the sheet models. Entries flagged False are path-dependent:
# the PNC Recommendation only exists if a PNC was held, and the Advance Payment format
# only if an advance is actually sought. cascade_check.py asserts this table is the
# exact inversion of the sheet's "Required for" column.
PREREQ_FORMATS = {
    "pbo":             [("tec_statement", True)],
    "pnc_req":         [("tec_statement", True), ("commercial_eval", True),
                        ("comparative_statement", True), ("price_justification", True)],
    "pnc_rec":         [("pnc_agenda", True)],
    "pp":              [("tec_statement", True), ("commercial_eval", True),
                        ("comparative_statement", True), ("price_justification", True),
                        ("pnc_recommendation", False), ("advance_payment", False)],
    "po":              [("purchase_proposal", True)],
    "po_amendment":    [("purchase_order", True), ("hal_contract", True)],
    "advance_payment": [("advance_payment", True)],
}

# -- Block 2 -- the decision cascade -----------------------------------------
# One node per decision point. `owner` is the sheet's "Note Can only be
# Generated by" row; `stage_no` is its stage column (1-8, None pre-tender).
# Each option: (note id in stages.ALL_STAGES, label, next node, recommend rule).
#   next = None  -> terminal (file closed)
#   recommend    -> name of a rules.py predicate; True marks the option "advised"
NODES = {
    "provisioning": {
        "stage_no": None, "owner": INDENTING, "checklist": True,
        "title": "Provisioning -- raise the indent (N1)",
        "description": "Tender Document is prepared directly from Provisioning Checklist + 72 STC clauses without separate note generation.",
        "options": [
            ("provisioning", "PROVISIONING NOTE (N1)", "tender_opened", None),
        ],
    },
    "tender_opened": {
        "stage_no": 1, "owner": TENDERING,
        "title": "Tender opened -- post tender opening scenario (N2)",
        "options": [
            ("emd", "EMD STAGE ACCEPTANCE NOTE (N2)", "post_emd", None),
            ("retender", "RETENDER NOTE", "post_retender", "retender_required"),
            ("tec_req", "TEC REQ NOTE (N2)", "tec_stage", None),
        ],
    },
    "post_emd": {
        "stage_no": 2, "owner": TENDERING,
        "title": "After EMD stage acceptance",
        "options": [
            ("tec_req", "TEC REQ NOTE", "tec_stage", None),
            ("retender", "RETENDER NOTE", "post_retender", "retender_required"),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "post_retender": {
        "stage_no": 2, "owner": TENDERING,
        "title": "After retender",
        "options": [
            ("tec_req", "TEC REQ NOTE", "tec_stage", None),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "tec_stage": {
        "stage_no": 3, "owner": INDENTING,
        "title": "Technical evaluation -- with the TEC / indenting agency",
        "options": [
            ("tec_query", "TEC QUERY NOTE", "tec_stage", None),
            ("tec_report", "TEC REPORT NOTE", "post_tec_report", None),
        ],
    },
    "post_tec_report": {
        "stage_no": 4, "owner": TENDERING,
        "title": "TEC report received -- back with the tendering agency",
        "options": [
            ("pbo", "PRICE BID OPENING NOTE", "post_pbo", None),
            ("retender", "RETENDER NOTE", "post_retender", "retender_required"),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "post_pbo": {
        "stage_no": 4, "owner": TENDERING,
        "title": "Price bids opened -- L1 established",
        "options": [
            ("pnc_req", "PNC REQ NOTE", "pnc_stage", "pnc_required"),
            ("pp", "PP NOTE  (straight to proposal, no negotiation)", "post_pp", None),
            ("retender", "RETENDER NOTE", "post_retender", "retender_required"),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "pnc_stage": {
        "stage_no": 5, "owner": TENDERING,
        "title": "PNC approved -- negotiation held",
        "options": [
            ("pnc_rec", "PNC RECOMMENDATION", "post_pnc_rec", None),
            ("retender", "RETENDER NOTE", "post_retender", "retender_required"),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "post_pnc_rec": {
        "stage_no": 6, "owner": TENDERING,
        "title": "PNC recommendation on file",
        "options": [
            ("pp", "PP NOTE", "post_pp", None),
            ("advance_payment", "ADVANCE PAYMENT NOTE", "post_pnc_rec", None),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
    "post_pp": {
        "stage_no": 7, "owner": TENDERING,
        "title": "Purchase proposal approved by CFA",
        "options": [
            # Sheet column L holds PO + HAL CONTRACT and nothing else -- no retender,
            # no short closure, no advance payment at this stage.
            ("po", "PO + HAL CONTRACT", "post_po", None),
        ],
    },
    "post_po": {
        "stage_no": 8, "owner": TENDERING,
        "title": "PO / contract placed",
        "options": [
            ("po_amendment", "PO AMENDMENT NOTE", "post_po", None),
            ("short_closure", "SHORT CLOSURE NOTE", None, None),
        ],
    },
}

START = "provisioning"

# Sheet cell G18 -- what a short closure means for the requisition.
SHORT_CLOSURE_MSG = "Requirement is closed and no more further action on this requisition no."


def option(node_id, note_id):
    """The (note, label, next, recommend) tuple for note_id at node_id."""
    for opt in NODES[node_id]["options"]:
        if opt[0] == note_id:
            return opt
    return None


def checklist_owner(label):
    for _, items in CHECKLIST:
        for lbl, own in items:
            if lbl == label:
                return own
    return None
