"""Asserts cascade.py is a faithful copy of the responsibility-cascading sheet.

Reads the xlsx directly and compares, cell by cell:
  * block 2 -- the notes listed in each stage column F..M (= stage 1..8)
  * block 2 -- row 23, "Note Can only be Generated by", per stage column
  * block 1 -- the input checklist B6:C25 and its per-line responsibility
  * block 3 -- the post-tender formats F26:H35, responsibility and "Required for"

Run:  conda run -n hal python ai/cascade_check.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import openpyxl

import cascade
from cascade import INDENTING, NODES, TENDERING
from stages import ALL_STAGES

XLSX = (Path(__file__).resolve().parents[1] / "sampleData" /
        "HAL PURCHASE FORMATS dt 22.06.2026" /
        "Note & Format Generation Stages and responsibility cascadeing.xlsx")

# Stage column letter -> stage number, from sheet row 24 (E24 "Stage", F24=1 .. M24=8).
STAGE_COLS = {"F": 1, "G": 2, "H": 3, "I": 4, "J": 5, "K": 6, "L": 7, "M": 8}

# Each note id and the exact sheet spelling(s) it appears under. The sheet has two
# typos ("ACCPETANCE", "NEGOTAITAION") and abbreviates the stage-1 retender cell to
# "RETENDER"; they are matched verbatim rather than corrected.
NOTE_NAMES = {
    "emd":             ["EMD STAGE ACCPETANCE"],
    "retender":        ["RETENDER NOTE", "RETENDER"],
    "tec_req":         ["TEC REQ NOTE"],
    "short_closure":   ["SHORT CLOSURE NOTE"],
    "tec_query":       ["TEC QUERY NOTE"],
    "tec_report":      ["TEC REPORT NOTE"],
    "pbo":             ["PRICE BID OPENING NOTE"],
    "pnc_req":         ["PNC REQ NOTE"],
    "pnc_rec":         ["PNC RECOMMENDATION"],
    "pp":              ["PP NOTE"],
    "advance_payment": ["ADVANCE PAYMENT NOTE"],
    "po":              ["PO + HAL CONTRACT"],
    "po_amendment":    ["PO AMENDMENT NOTE"],
}

# Cells in the stage columns that are captions, not notes.
CAPTIONS = {"TENDER OPENED", "POST TENDER OPENING SCENARIO", "RESPONSIBILITY",
            "REQUIRED FOR", "FORMATS POST TENDER OPENING", "STAGE",
            "TENDERING AGENCY", "INDENTING AGENCY",
            "NOTE CAN ONLY BE GENERATED BY", cascade.SHORT_CLOSURE_MSG.upper().rstrip(".")}

# Block 3 rows: sheet format name -> (responsibility, "Required for", fid in cascade)
BLOCK3_ROWS = range(26, 36)

results = []


def check(ok, label, detail=""):
    results.append((bool(ok), label, detail))
    print(f"  {'ok  ' if ok else 'FAIL'} {label}" + (f"   -- {detail}" if detail and not ok else ""))
    return bool(ok)


def norm(s):
    return " ".join(str(s).split()).strip().upper().rstrip(".")


def note_of(cell_text):
    t = norm(cell_text)
    for nid, names in NOTE_NAMES.items():
        if t in [norm(n) for n in names]:
            return nid
    return None


def main():
    ws = openpyxl.load_workbook(XLSX, data_only=True)["Sheet1"]
    get = lambda col, row: ws[f"{col}{row}"].value

    print(f"\n{'='*70}\n CASCADE vs SHEET -- {XLSX.name}\n{'='*70}")

    # ── block 2, row 24: the stage numbering itself ──────────────────────────
    print("\n block 2 -- stage numbering (row 24)")
    for col, n in STAGE_COLS.items():
        check(get(col, 24) == n, f"column {col} is stage {n}", f"sheet says {get(col, 24)!r}")

    # ── block 2: notes possible per stage column ─────────────────────────────
    print("\n block 2 -- notes possible at each stage (columns F..M, rows 4..21)")
    unknown = []
    for col, stage_no in STAGE_COLS.items():
        sheet_notes = set()
        for row in range(4, 22):
            v = get(col, row)
            if v in (None, ""):
                continue
            if norm(v) in CAPTIONS:
                continue
            nid = note_of(v)
            if nid:
                sheet_notes.add(nid)
            else:
                unknown.append(f"{col}{row}={v!r}")
        coded = {opt[0] for nid_, node in NODES.items() if node["stage_no"] == stage_no
                 for opt in node["options"]}
        check(sheet_notes == coded, f"stage {stage_no} (col {col}): {sorted(sheet_notes)}",
              f"sheet {sorted(sheet_notes)} != cascade {sorted(coded)}")
    check(not unknown, "every populated stage-column cell is a recognised note or caption",
          f"unmatched: {unknown}")

    # ── block 2, row 23: who may generate ───────────────────────────────────
    print("\n block 2 -- 'Note Can only be Generated by' (row 23)")
    for col, stage_no in STAGE_COLS.items():
        want = norm(get(col, 23))
        owners = {node["owner"] for node in NODES.values() if node["stage_no"] == stage_no}
        coded = {norm(cascade.AGENCY_LABEL[o]) for o in owners}
        check(coded == {want}, f"stage {stage_no} (col {col}) -> {want.title()}",
              f"sheet {want!r} != cascade {coded}")

    # pre-tender ownership comes from block 1, not block 2
    check(NODES["provisioning"]["owner"] == INDENTING,
          "provisioning node owned by Indenting Agency (block 1, C6:C11)")
    check(NODES["tender_doc"]["owner"] == TENDERING,
          "tender-document node owned by Tendering Agency (block 1, C13 + D7)")

    # ── block 1: the input checklist and its ownership ───────────────────────
    print("\n block 1 -- input checklist responsibility (B6:C25)")
    sheet_pairs = []
    for row in range(6, 26):
        label, resp = get("B", row), get("C", row)
        if label in (None, "") or resp in (None, ""):
            continue
        sheet_pairs.append((norm(label), norm(resp)))
    coded_counts = {INDENTING: 0, TENDERING: 0}
    for _, items in cascade.CHECKLIST:
        for _lbl, own in items:
            coded_counts[own] += 1
    sheet_counts = {
        INDENTING: sum(1 for _, r in sheet_pairs if r == norm(cascade.AGENCY_LABEL[INDENTING])),
        TENDERING: sum(1 for _, r in sheet_pairs if r == norm(cascade.AGENCY_LABEL[TENDERING])),
    }
    check(sheet_counts == coded_counts,
          f"line counts per agency: Indenting {sheet_counts[INDENTING]}, "
          f"Tendering {sheet_counts[TENDERING]}",
          f"sheet {sheet_counts} != cascade {coded_counts}")

    # ── block 3: formats, responsibility, required-for ───────────────────────
    print("\n block 3 -- formats post tender opening (F26:H35)")
    sheet_fmts = []
    for row in BLOCK3_ROWS:
        name, resp, req = get("F", row), get("G", row), get("H", row)
        if name in (None, ""):
            continue
        sheet_fmts.append((norm(name), norm(resp), norm(req)))
    check(len(sheet_fmts) == len(cascade.POST_TENDER_FORMATS),
          f"{len(sheet_fmts)} format rows",
          f"sheet {len(sheet_fmts)} != cascade {len(cascade.POST_TENDER_FORMATS)}")

    coded_fmts = {norm(n): (norm(cascade.AGENCY_LABEL[r]), norm(req), fid)
                  for n, r, req, fid in cascade.POST_TENDER_FORMATS}
    # sheet spelling -> cascade spelling for the two rows the sheet misspells/abbreviates
    ALIAS = {"AGENDA OF NEGOTAITAION": "AGENDA OF NEGOTIATION",
             "COMMERCIAL EVALAUTION REPORT": "COMMERCIAL EVALUATION REPORT",
             "PRICE JUSTIFCATION STATEMENT": "PRICE JUSTIFICATION STATEMENT"}
    for name, resp, req in sheet_fmts:
        key = ALIAS.get(name, name)
        entry = coded_fmts.get(key)
        if not check(entry is not None, f"format present: {name.title()}", "not in cascade"):
            continue
        c_resp, _c_req, fid = entry
        check(c_resp == resp, f"  responsibility of {key.title()} = {resp.title()}",
              f"sheet {resp!r} != cascade {c_resp!r}")
        # "Required for" -> PREREQ_FORMATS must list this fid against each named note
        want_notes = set()
        for token, nid in (("PRICE BID OPENING", "pbo"), ("PNC APPROVAL", "pnc_rec"),
                           ("PNC RECOMMENDATION", "pnc_rec"), ("PURCHASE PROPOSAL", "pp"),
                           ("PURCHASE ORDER", "po"), ("CONTRACT", "po"),
                           ("PO AMENDMENT", "po_amendment"),
                           ("ADVANCE PAYMENT NOTE", "advance_payment")):
            if token in req:
                want_notes.add(nid)
        if "PNC" in req and "PNC APPROVAL" not in req and "PNC RECOMMENDATION" not in req:
            want_notes.add("pnc_req")          # bare "PNC" = the PNC request
        if "CONTRACT/PO AMENDMENT" in req.replace(" ", ""):
            want_notes = {"po", "po_amendment"}
        got_notes = {nid for nid, lst in cascade.PREREQ_FORMATS.items()
                     if fid in [f for f, _ in lst]}
        # a format is not a prerequisite of the note that produces it
        want_notes = {n for n in want_notes if fid not in ALL_STAGES.get(n, {}).get('formats', ())}
        check(want_notes <= got_notes, f"  '{req}' -> prereq of {sorted(want_notes)}",
              f"missing {sorted(want_notes - got_notes)} (cascade has {sorted(got_notes)})")

    bad = [l for ok, l, _ in results if not ok]
    print(f"\n{'='*70}")
    print(f" {len(results) - len(bad)}/{len(results)} checks passed"
          + ("" if not bad else f" -- {len(bad)} FAILED"))
    print(f"{'='*70}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
