"""Interactive, decision-based driver for the HAL note cascade.

Walks cascade.NODES one decision at a time. At every node the sheet names exactly
one agency that may raise the note ("Note Can only be Generated by"), so the CLI
enforces it: acting out of turn is refused, and the file must be handed over to
the other agency first. Whatever note you pick is generated for real through
pipeline.run_stage() -- same deterministic formats, same carry-forward, same SLM.

Run it from run.py (default) or directly:
    conda run -n hal python ai/interactive.py [--agency Indenting|Tendering]
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import cascade
import rules
from cascade import AGENCY_LABEL, INDENTING, NODES, TENDERING
from case_object import CaseObject
from load_inputs import load, to_stage_inputs
from pipeline import run_stage
from stages import ALL_STAGES, REF
from tools import pdf_writer

SEP = "=" * 68
SUB = "-" * 68
QUIT = "\x00"

HERE = Path(__file__).parent
CASE_INPUT = HERE / "case_input.json"
OUT = HERE / "outputs"


# ── small terminal helpers ───────────────────────────────────────────────────
def _ask(prompt):
    """Read a line; QUIT sentinel on ^C / ^D / EOF."""
    try:
        return input(prompt).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return QUIT


def _yes(prompt, default=True):
    d = "Y/n" if default else "y/N"
    a = _ask(f"{prompt} [{d}]: ")
    if a == QUIT:
        return QUIT
    if not a:
        return default
    return a.lower().startswith("y")


def _txt(v, n=54):
    s = "; ".join(str(x) for x in v) if isinstance(v, list) else str(v)
    s = s.replace("\n", " ")
    return s if len(s) <= n else s[: n - 1] + "..."


def _agency(a):
    return AGENCY_LABEL[a].upper()


# ── screens ─────────────────────────────────────────────────────────────────
def pick_agency(preset=None):
    if preset:
        return preset
    print(f"\n{SEP}\n WHO IS AT THE DESK?\n{SEP}")
    print(" The cascade sheet recognises two agencies. Every note belongs to one\n"
          " of them, and the file has to be handed over to cross between them.\n")
    for i, a in enumerate(cascade.AGENCIES, 1):
        owns = [n["title"] for n in NODES.values() if n["owner"] == a]
        print(f"   {i}) {AGENCY_LABEL[a]:<18} -- owns {len(owns)} of {len(NODES)} decision points")
    while True:
        a = _ask("\n you are [2]: ")
        if a == QUIT:
            return None
        a = a or "2"
        if a in ("1", "2"):
            return cascade.AGENCIES[int(a) - 1]
        print(" ! enter 1 or 2")


def show_checklist(active, state):
    """Block 1 of the sheet -- inputs for tender document generation."""
    print(f"\n{SUB}\n INPUTS FOR TENDER DOCUMENT GENERATION  (sheet block 1)\n{SUB}")
    mine = 0
    for group, items in cascade.CHECKLIST:
        print(f"\n  {group}")
        for label, owner in items:
            done = label in state["enclosed"]
            if owner == active:
                mine += 1
                mark = "x" if done else " "
                print(f"   [{mark}] {label}")
            else:
                mark = "x" if done else " "
                print(f"   [{mark}] {label}   <- {AGENCY_LABEL[owner]}")
    print(f"\n  {mine} of these lines are yours ({AGENCY_LABEL[active]}).")
    ok = _yes("  all of your lines enclosed with the file?")
    if ok == QUIT:
        return QUIT
    for _, items in cascade.CHECKLIST:
        for label, owner in items:
            if owner == active and ok:
                state["enclosed"].add(label)
    if not ok:
        pend = _ask("  which are still pending (free text, Enter to skip): ")
        if pend == QUIT:
            return QUIT
        if pend:
            state["pending"].append(f"{AGENCY_LABEL[active]}: {pend}")
            print(f"  ! recorded as pending -- the note will be raised with enclosures incomplete")
    return True


def show_formats(case):
    """Block 3 of the sheet -- formats post tender opening, and who owns them."""
    print(f"\n{SUB}\n FORMATS POST TENDER OPENING  (sheet block 3)\n{SUB}")
    print(f"  {'format':<32}{'responsibility':<20}{'on file':<9}required for")
    for name, resp, req_for, fid in cascade.POST_TENDER_FORMATS:
        on = "yes" if fid in case.formats else "-"
        print(f"  {name:<32}{AGENCY_LABEL[resp]:<20}{on:<9}{req_for}")


def eval_rule(name, case):
    """True / False / None when the rule's inputs are not on file yet."""
    need = rules.RULE_INPUTS.get(name, [])
    absent = [k for k in need if case.data.get(k) in (None, "", [])]
    if absent:
        return None, absent
    return bool(getattr(rules, name)(case.data)), []


def prereq_warnings(note_id, case):
    """Block 3's 'Required for' column, checked before a note is raised.

    Formats the note itself produces are not prerequisites -- the PNC Request, for
    instance, is where the Comparative Statement and Price Justification are drawn
    up, so the sheet's "Required for: PNC" means produced-with, not needed-before.
    """
    own = set(ALL_STAGES[note_id]["formats"])
    missing = [(f, req) for f, req in cascade.PREREQ_FORMATS.get(note_id, [])
               if f not in case.formats and f not in own]
    for fid, required in missing:
        owner = cascade.FORMAT_OWNER.get(fid)
        who = AGENCY_LABEL[owner] if owner else "?"
        kind = "required" if required else "if applicable"
        print(f" ! {kind} format not on file: {cascade.FORMAT_TITLE.get(fid, fid)}"
              f"  (responsibility: {who})")
    return missing


def collect_inputs(note_id, seeded, case):
    """Field-by-field input for the note being raised."""
    cfg = ALL_STAGES[note_id]
    pre = dict(seeded.get(note_id) or {})
    fields = cfg["new"]
    have = [k for k in fields if pre.get(k) not in (None, "", [])]

    if have:
        print(f"\n [{note_id}] {len(have)}/{len(fields)} fields seeded from case_input.json:")
        for k in have:
            print(f"     {k:<24} {_txt(pre[k])}")
        edit = _yes(" edit any field?", default=False)
        if edit == QUIT:
            return QUIT
        if not edit:
            return pre
    else:
        print(f"\n [{note_id}] no seeded data for this note -- enter it now"
              f" (Enter skips a field):")

    for k in fields:
        cur = pre.get(k)
        shown = f" [{_txt(cur, 40)}]" if cur not in (None, "", []) else ""
        a = _ask(f"     {k}{shown}: ")
        if a == QUIT:
            return QUIT
        if not a:
            continue
        if a == "-":
            pre.pop(k, None)
        elif isinstance(cur, list) or ";" in a:
            pre[k] = [p.strip() for p in a.split(";") if p.strip()]
        else:
            pre[k] = a
    return pre


def node_menu(node_id, active, case, state):
    """Render one decision point. Returns ('note', id) | ('cmd', key) | None."""
    node = NODES[node_id]
    stage = f"STAGE {node['stage_no']}" if node["stage_no"] else "PRE-TENDER"
    print(f"\n{SEP}\n {stage}  ::  {node['title']}\n{SEP}")
    print(f" note can only be generated by : {_agency(node['owner'])}")
    print(f" at the desk                   : {AGENCY_LABEL[active]}"
          f"{'  (ok)' if node['owner'] == active else '  (WRONG AGENCY)'}")
    if state["path"]:
        print(f" file so far                   : {' > '.join(s['note'] for s in state['path'])}")

    if node["owner"] != active:
        print(f"\n {AGENCY_LABEL[active]} cannot raise any note at this stage."
              f"\n The file has to move to the {AGENCY_LABEL[node['owner']]} first.")
        print(f"\n   h) hand the file over to the {AGENCY_LABEL[node['owner']]}"
              f"\n   f) formats on file"
              f"\n   q) save and quit")
        while True:
            a = _ask("\n choose [h]: ")
            if a == QUIT:
                return ("cmd", "q")
            a = (a or "h").lower()
            if a in ("h", "f", "q"):
                return ("cmd", a)
            print(" ! h, f or q")

    print("\n notes possible at this stage:")
    opts = node["options"]
    for i, (note_id, label, nxt, rule) in enumerate(opts, 1):
        tag = ""
        if rule:
            ok, absent = eval_rule(rule, case)
            if ok is None:
                tag = f"   ({rule}(): undecided, {', '.join(absent)} not on file yet)"
            else:
                tag = f"   <- advised ({rule}() = True)" if ok else f"   ({rule}() = False)"
        if nxt is None:
            tag += "   [closes the file]"
        if note_id in state["raised"]:
            tag += f"   [already raised x{state['raised'][note_id]}]"
        print(f"   {i}) {label}{tag}")
    print("\n   f) formats on file   v) view the file   h) hand over   q) save and quit")

    while True:
        a = _ask("\n choose [1]: ")
        if a == QUIT:
            return ("cmd", "q")
        a = (a or "1").lower()
        if a in ("f", "v", "h", "q"):
            return ("cmd", a)
        if a.isdigit() and 1 <= int(a) <= len(opts):
            return ("note", opts[int(a) - 1][0])
        print(f" ! 1-{len(opts)}, or f / v / h / q")


# ── the session ─────────────────────────────────────────────────────────────
def session(seeded, agency=None, max_tokens=800):
    case = CaseObject()
    state = {"path": [], "raised": {}, "handovers": 0, "enclosed": set(), "pending": []}

    active = pick_agency(agency)
    if not active:
        return None, state

    node_id = cascade.START
    closed = None

    while node_id:
        node = NODES[node_id]
        sel = node_menu(node_id, active, case, state)
        if sel is None:
            break
        kind, val = sel

        if kind == "cmd":
            if val == "q":
                break
            if val == "f":
                show_formats(case)
                continue
            if val == "v":
                last = state["path"][-1]["note"] if state["path"] else None
                body = case.full_output(last) if last else ""
                print(f"\n{SUB}\n THE FILE AS IT STANDS -- {last or 'empty'}\n{SUB}\n{body or '(nothing raised yet)'}")
                continue
            if val == "h":
                other = TENDERING if active == INDENTING else INDENTING
                active = other
                state["handovers"] += 1
                print(f"\n >> file handed over to the {AGENCY_LABEL[other]}"
                      f"  (hand-over #{state['handovers']})")
                continue

        note_id = val
        _, label, nxt, rule = cascade.option(node_id, note_id)

        # An option the rules advise against is allowed, but has to be owned.
        advised = [o for o in node["options"] if o[3] and eval_rule(o[3], case)[0] is True]
        if advised and note_id not in [o[0] for o in advised]:
            names = ", ".join(o[1] for o in advised)
            print(f"\n ! the rules advise {names} at this stage.")
            go = _yes(f" raise {label} anyway?", default=False)
            if go == QUIT or not go:
                continue

        if node.get("checklist"):
            if show_checklist(active, state) == QUIT:
                break

        prereq_warnings(note_id, case)

        inp = collect_inputs(note_id, seeded, case)
        if inp == QUIT:
            break

        if note_id in state["raised"]:
            print(f" ! {ALL_STAGES[note_id]['note']} was already raised -- this version supersedes it")

        run_stage(note_id, case, inp, max_tokens=max_tokens)
        state["raised"][note_id] = state["raised"].get(note_id, 0) + 1
        state["path"].append({"node": node_id, "note": note_id, "agency": active,
                              "stage_no": node["stage_no"], "label": label})

        if nxt is None:
            closed = note_id
            print(f"\n{SEP}\n FILE CLOSED -- {ALL_STAGES[note_id]['note']}\n{SEP}")
            print(f" {cascade.SHORT_CLOSURE_MSG}")
            break
        node_id = nxt

    return case, dict(state, closed=closed)


def summary(case, state):
    print(f"\n{SEP}\n CASCADE ACTUALLY WALKED\n{SEP}")
    if not state["path"]:
        print(" nothing raised.")
        return
    print(f"  {'#':<3}{'stage':<8}{'note':<34}raised by")
    for i, s in enumerate(state["path"], 1):
        st = s["stage_no"] or "-"
        print(f"  {i:<3}{str(st):<8}{ALL_STAGES[s['note']]['note']:<34}{AGENCY_LABEL[s['agency']]}")

    by = {INDENTING: [], TENDERING: []}
    for s in state["path"]:
        by[s["agency"]].append(ALL_STAGES[s["note"]]["note"])
    print(f"\n  responsibility split")
    for a in cascade.AGENCIES:
        print(f"    {AGENCY_LABEL[a]:<18} {len(by[a])} note(s): {', '.join(by[a]) or '-'}")
    print(f"    hand-overs between agencies: {state['handovers']}")

    if case.formats:
        print(f"\n  formats generated ({len(case.formats)})")
        for fid, d in case.formats.items():
            owner = cascade.FORMAT_OWNER.get(fid)
            who = f"  [{AGENCY_LABEL[owner]}]" if owner else ""
            print(f"    {d.get('format', fid)}{who}")
    if state["pending"]:
        print(f"\n  ! enclosures recorded as pending")
        for p in state["pending"]:
            print(f"    {p}")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Interactive HAL note cascade")
    ap.add_argument("--agency", choices=cascade.AGENCIES, help="skip the who-are-you prompt")
    ap.add_argument("--case", default=str(CASE_INPUT), help="seed data (default ai/case_input.json)")
    ap.add_argument("--max-tokens", type=int, default=800)
    a = ap.parse_args(argv)

    print(f"\n{SEP}\n HAL PROCUREMENT -- INTERACTIVE NOTE CASCADE\n{SEP}")
    print(" source: sampleData/HAL PURCHASE FORMATS dt 22.06.2026/\n"
          "         Note & Format Generation Stages and responsibility cascadeing.xlsx")
    print(f" seed  : {Path(a.case).name}  (facts only -- generated notes are never inputs)")

    seeded = to_stage_inputs(load(a.case))
    case, state = session(seeded, agency=a.agency, max_tokens=a.max_tokens)
    if case is None:
        print("\n aborted -- nothing written.")
        return 0

    summary(case, state)

    if state["path"]:
        OUT.mkdir(parents=True, exist_ok=True)
        case.save(str(OUT / "case_full.json"))
        print(f"\n case saved -> {OUT / 'case_full.json'}")
        # Number the PDFs in the order this file was actually walked, not by the
        # linear ORDER seq -- the cascade can revisit and reorder notes.
        walked = list(dict.fromkeys(s["note"] for s in state["path"]))
        meta = {sid: {"note": ALL_STAGES[sid]["note"], "formats": ALL_STAGES[sid]["formats"],
                      "seq": walked.index(sid) if sid in walked else ALL_STAGES[sid]["seq"],
                      "ref": REF.get(sid, sid)} for sid in ALL_STAGES}
        pdfs = pdf_writer.write_case_pdf(case, meta, str(OUT / "pdf"))
        print(f" {len(pdfs)} note PDF(s) -> {OUT / 'pdf'}")
        for p in pdfs:
            print(f"   {p}")
    print(f"\n{SEP}\n DONE\n{SEP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
