import { useEffect, useMemo, useState } from 'react';
import DataGrid from '../../components/DataGrid.jsx';
import { REGISTER_COLUMNS, REGISTER_CSV_COLUMNS } from '../../config/contractColumns.jsx';
import { fetchRegister } from '../../lib/contractsApi.js';
import { downloadCsv, toCsv } from '../../lib/csv.js';

// The contract register: every generated contract with the client's full field list.
// Data is server-denormalised — this screen only filters and exports.
const FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'draft', label: 'Draft' },
  { id: 'finalised', label: 'Finalised' }
];

export default function Register() {
  const [contracts, setContracts] = useState(null);
  const [filter, setFilter] = useState('all');
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchRegister()
      .then((d) => setContracts(d.contracts))
      .catch((e) => setError(e.message));
  }, []);

  const rows = useMemo(
    () => contracts && contracts.filter((c) => filter === 'all' || c.status === filter),
    [contracts, filter]
  );

  const exportCsv = () =>
    downloadCsv('contract-register.csv', toCsv(REGISTER_CSV_COLUMNS, rows || []));

  return (
    <section className="screen">
      <h1 className="screen-title">Contract Register</h1>
      <p className="screen-sub">
        All contracts generated by the application — number, parties, value, references and
        the generator's credentials. Open a contract to view, finalise or print it.
      </p>

      {error && <div className="banner banner-error">{error}</div>}

      <div className="pill-row">
        {FILTERS.map((f) => (
          <button
            key={f.id}
            type="button"
            className={'btn btn-inline' + (filter === f.id ? '' : ' btn-secondary')}
            onClick={() => setFilter(f.id)}
          >
            {f.label}
          </button>
        ))}
        <span style={{ flex: 1 }} />
        <button type="button" className="btn btn-secondary btn-inline" onClick={exportCsv} disabled={!rows?.length}>
          Export CSV
        </button>
      </div>

      <DataGrid columns={REGISTER_COLUMNS} rows={rows} emptyMessage="No contracts generated yet." />
    </section>
  );
}
