import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import DataGrid from '../../components/DataGrid.jsx';
import { PP_APPROVED_COLUMNS, REGISTER_COLUMNS, REGISTER_CSV_COLUMNS } from '../../config/contractColumns.jsx';
import { fetchPpApproved, fetchRegister } from '../../lib/contractsApi.js';
import { downloadCsv, toCsv } from '../../lib/csv.js';

// The contract register: every generated contract with the client's full field list, plus
// the CON-01 queue (requisitions whose PP is approved and that have no contract yet). Data
// is server-denormalised — this screen only filters and exports. `?filter=` deep-links the
// Portal Hub cards: approved_pp | draft | finalised | released.
const FILTERS = [
  { id: 'all', label: 'All contracts' },
  { id: 'approved_pp', label: 'PP approved — awaiting contract' },
  { id: 'draft', label: 'Draft' },
  { id: 'finalised', label: 'Finalised' },
  { id: 'released', label: 'Released' }
];

export default function Register() {
  const [params, setParams] = useSearchParams();
  const filter = FILTERS.some((f) => f.id === params.get('filter')) ? params.get('filter') : 'all';
  const [contracts, setContracts] = useState(null);
  const [queue, setQueue] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchRegister()
      .then((d) => setContracts(d.contracts))
      .catch((e) => setError(e.message));
    fetchPpApproved()
      .then((d) => setQueue(d.requisitions))
      .catch((e) => setError(e.message));
  }, []);

  const rows = useMemo(
    () => contracts && contracts.filter((c) => filter === 'all' || filter === 'approved_pp' || c.status === filter),
    [contracts, filter]
  );

  const exportCsv = () => downloadCsv('contract-register.csv', toCsv(REGISTER_CSV_COLUMNS, rows || []));

  return (
    <section className="screen">
      <h1 className="screen-title">Contract Register</h1>
      <p className="screen-sub">
        All contracts generated by the application — number, parties, value, references and
        the generator's credentials — and the requisitions waiting for one. Open a contract to view, finalise, release or print it.
      </p>

      {error && <div className="banner banner-error">{error}</div>}

      <div className="pill-row">
        {FILTERS.map((f) => (
          <button
            key={f.id}
            type="button"
            className={'btn btn-inline' + (filter === f.id ? '' : ' btn-secondary')}
            onClick={() => setParams(f.id === 'all' ? {} : { filter: f.id })}
          >
            {f.label}
            {f.id === 'approved_pp' && queue ? ` (${queue.length})` : ''}
          </button>
        ))}
        <span style={{ flex: 1 }} />
        <button type="button" className="btn btn-secondary btn-inline" onClick={exportCsv} disabled={!rows?.length}>
          Export CSV
        </button>
      </div>

      {filter === 'approved_pp' ? (
        <>
          <h2 className="form-section-title">PP approved — no contract yet (CON-01)</h2>
          <DataGrid columns={PP_APPROVED_COLUMNS} rows={queue} rowKey="id" emptyMessage="Every PP-approved requisition already has a contract." />
          <p className="tracker-source">Source: requisition register status (derived from the noting proposal, PO and contract on file).</p>
        </>
      ) : (
        <DataGrid columns={REGISTER_COLUMNS} rows={rows} emptyMessage="No contracts in this view." />
      )}
    </section>
  );
}
