// The responsibility cascade as data — extracted from server/routes/ai.js so the route
// that publishes it and the walker that executes it share one copy.
//
// Source of truth, and nothing here is invented:
//
//   sampleData/HAL PURCHASE FORMATS dt 22.06.2026/
//       Note & Format Generation Stages and responsibility cascadeing.xlsx  [Sheet1]
//
// The sheet recognises exactly two actors. Row 23, "Note Can only be Generated by", names
// the single agency allowed to raise the notes in each stage column — which is why acting
// out of turn is refused here rather than merely warned about, and the file has to be
// handed over first.
//
// The sheet holds no conditional logic of its own: it says WHICH notes are possible at a
// stage and WHO may raise them, never WHEN to prefer one. So every edge is selectable, and
// the only two preferences (pnc_required, retender_required) come from rules.js, are
// labelled with their rule name, and are never binding.

export const AGENCIES = ['Indenting', 'Tendering'];
export const START = 'provisioning';

export const SHORT_CLOSURE_MESSAGE =
  'Requirement is closed and no more further action on this requisition no.';

// Note title / phase / owning agency / annexures, per note. Mirrors ai/stages.py.
export const STAGE_META = {
  provisioning: { seq: 1, phase: 'PROVISIONING', agency: 'Indenting', title: 'Provisioning Note (N1)', ref: 'Provisioning_Note', formats: ['mpr_car'] },
  emd: { seq: 2, phase: 'TENDERING', agency: 'Tendering', title: 'EMD Stage Acceptance Note (N2)', ref: 'EMD_Stage_Acceptance', formats: [] },
  tec_req: { seq: 3, phase: 'TECHNICAL', agency: 'Tendering', title: 'TEC Request Note', ref: 'TEC_Req', formats: [] },
  tec_report: { seq: 4, phase: 'TECHNICAL', agency: 'Indenting', title: 'TEC Report Note', ref: 'TEC_Report', formats: ['tec_statement'] },
  pbo: { seq: 5, phase: 'COMMERCIAL', agency: 'Tendering', title: 'Price Bid Opening Note', ref: 'PBO_Req', formats: ['tec_statement'] },
  pnc_req: { seq: 6, phase: 'COMMERCIAL', agency: 'Tendering', title: 'PNC Request Note', ref: 'PNC_Req', formats: ['commercial_eval', 'comparative_statement', 'price_justification', 'pnc_agenda'] },
  pnc_rec: { seq: 7, phase: 'COMMERCIAL', agency: 'Tendering', title: 'PNC Recommendation Note', ref: 'PNC_Recc', formats: ['pnc_recommendation'] },
  pp: { seq: 8, phase: 'COMMERCIAL', agency: 'Tendering', title: 'Purchase Proposal Note', ref: 'Purchase_Proposal', formats: ['purchase_proposal'] },
  po: { seq: 9, phase: 'COMMERCIAL', agency: 'Tendering', title: 'Purchase Order + HAL Contract', ref: 'PO_HAL_Contract', formats: ['purchase_order', 'hal_contract'] },
  retender: { seq: 10, phase: 'TENDERING', agency: 'Tendering', title: 'Retender Note', ref: 'Retender_Note', formats: [], needBased: true },
  short_closure: { seq: 11, phase: 'ANY', agency: 'Tendering', title: 'Short Closure Note', ref: 'Short_Closure_Note', formats: [], needBased: true, terminal: true },
  tec_query: { seq: 12, phase: 'TECHNICAL', agency: 'Indenting', title: 'TEC Query Note', ref: 'TEC_Query_Note', formats: [], needBased: true },
  advance_payment: { seq: 13, phase: 'COMMERCIAL', agency: 'Tendering', title: 'Advance Payment Note', ref: 'Advance_Payment_Note', formats: ['advance_payment'], needBased: true },
  po_amendment: { seq: 14, phase: 'COMMERCIAL', agency: 'Tendering', title: 'PO Amendment Note', ref: 'PO_Amendment_Note', formats: [], needBased: true }
};

// One node per decision point. `owner` is the sheet's row-23 agency; `next: null` is
// terminal (the file is closed). `recommend` names a rules.js predicate: when it comes out
// true the option is marked "advised", and choosing anything else needs a confirmation.
export const CASCADE_NODES = {
  provisioning: {
    stageNo: 1, owner: 'Indenting', checklist: true, title: 'Provisioning — raise the indent (N1)',
    description: 'The Tender Document is prepared directly from the Provisioning Checklist and the Standard Terms & Conditions (72 STC clauses), without a separate note.',
    options: [{ noteId: 'provisioning', label: 'PROVISIONING NOTE (N1)', next: 'tender_opened' }]
  },
  tender_opened: {
    stageNo: 2, owner: 'Tendering', title: 'Tender floated & opened — post tender opening scenario (N2)',
    options: [
      { noteId: 'emd', label: 'EMD STAGE ACCEPTANCE NOTE (N2)', next: 'post_emd' },
      { noteId: 'tec_req', label: 'TEC REQ NOTE (N2)', next: 'tec_stage' },
      { noteId: 'retender', label: 'RETENDER NOTE', next: 'post_retender', recommend: 'retender_required' }
    ]
  },
  post_emd: {
    stageNo: 3, owner: 'Tendering', title: 'After EMD stage acceptance',
    options: [
      { noteId: 'tec_req', label: 'TEC REQ NOTE', next: 'tec_stage' },
      { noteId: 'retender', label: 'RETENDER NOTE', next: 'post_retender', recommend: 'retender_required' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  post_retender: {
    stageNo: 2, owner: 'Tendering', title: 'After retender',
    options: [
      { noteId: 'tec_req', label: 'TEC REQ NOTE', next: 'tec_stage' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  tec_stage: {
    stageNo: 3, owner: 'Indenting', title: 'Technical evaluation — with the TEC / indenting agency',
    options: [
      { noteId: 'tec_query', label: 'TEC QUERY NOTE', next: 'tec_stage' },
      { noteId: 'tec_report', label: 'TEC REPORT NOTE', next: 'post_tec_report' }
    ]
  },
  post_tec_report: {
    stageNo: 4, owner: 'Tendering', title: 'TEC report received — back with the tendering agency',
    options: [
      { noteId: 'pbo', label: 'PRICE BID OPENING NOTE', next: 'post_pbo' },
      { noteId: 'retender', label: 'RETENDER NOTE', next: 'post_retender', recommend: 'retender_required' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  post_pbo: {
    stageNo: 4, owner: 'Tendering', title: 'Price bids opened — L1 established',
    options: [
      { noteId: 'pnc_req', label: 'PNC REQ NOTE', next: 'pnc_stage', recommend: 'pnc_required' },
      { noteId: 'pp', label: 'PP NOTE (straight to proposal, no negotiation)', next: 'post_pp' },
      { noteId: 'retender', label: 'RETENDER NOTE', next: 'post_retender', recommend: 'retender_required' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  pnc_stage: {
    stageNo: 5, owner: 'Tendering', title: 'PNC approved — negotiation held',
    options: [
      { noteId: 'pnc_rec', label: 'PNC RECOMMENDATION', next: 'post_pnc_rec' },
      { noteId: 'retender', label: 'RETENDER NOTE', next: 'post_retender', recommend: 'retender_required' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  post_pnc_rec: {
    stageNo: 6, owner: 'Tendering', title: 'PNC recommendation on file',
    options: [
      { noteId: 'pp', label: 'PP NOTE', next: 'post_pp' },
      { noteId: 'advance_payment', label: 'ADVANCE PAYMENT NOTE', next: 'post_pnc_rec' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  },
  post_pp: {
    stageNo: 7, owner: 'Tendering', title: 'Purchase proposal approved by CFA',
    // Sheet column L holds PO + HAL CONTRACT and nothing else — no retender, no short
    // closure, no advance payment at this stage.
    options: [{ noteId: 'po', label: 'PO + HAL CONTRACT', next: 'post_po' }]
  },
  post_po: {
    stageNo: 8, owner: 'Tendering', title: 'PO / contract placed',
    options: [
      { noteId: 'po_amendment', label: 'PO AMENDMENT NOTE', next: 'post_po' },
      { noteId: 'short_closure', label: 'SHORT CLOSURE NOTE', next: null }
    ]
  }
};

// Block 3 of the sheet — formats generated after tender opening, and who owns each.
export const POST_TENDER_FORMATS = [
  { id: 'tec_statement', title: 'TEC Report', owner: 'Indenting', requiredFor: 'Price Bid Opening, PNC & Purchase Proposal' },
  { id: 'commercial_eval', title: 'Commercial Evaluation Report', owner: 'Tendering', requiredFor: 'PNC & Purchase Proposal' },
  { id: 'comparative_statement', title: 'Comparative Statement', owner: 'Tendering', requiredFor: 'PNC & Purchase Proposal' },
  { id: 'price_justification', title: 'Price Justification Statement', owner: 'Tendering', requiredFor: 'PNC & Purchase Proposal' },
  { id: 'pnc_agenda', title: 'Agenda of Negotiation', owner: 'Tendering', requiredFor: 'PNC Approval & PNC Recommendation' },
  { id: 'pnc_recommendation', title: 'PNC Recommendation', owner: 'Tendering', requiredFor: 'Purchase Proposal' },
  { id: 'purchase_proposal', title: 'Purchase Proposal', owner: 'Tendering', requiredFor: 'Purchase Order / Contract' },
  { id: 'purchase_order', title: 'Purchase Order', owner: 'Tendering', requiredFor: 'Contract / PO Amendment' },
  { id: 'hal_contract', title: 'Contract', owner: 'Tendering', requiredFor: 'PO Amendment' },
  { id: 'advance_payment', title: 'Advance Payment Format', owner: 'Tendering', requiredFor: 'Advance Payment Note / Purchase Proposal' }
];

export const FORMAT_OWNER = Object.fromEntries(POST_TENDER_FORMATS.map((f) => [f.id, f.owner]));
export const FORMAT_TITLE = Object.fromEntries(POST_TENDER_FORMATS.map((f) => [f.id, f.title]));

// Block 3's "Required for" column, inverted: note -> [{ format, alwaysRequired }].
// A missing one is warned about, never blocked — a format owned by the other agency is
// exactly the hand-over the sheet models. Entries flagged false are path-dependent.
export const PREREQ_FORMATS = {
  pbo: [{ id: 'tec_statement', required: true }],
  pnc_req: [
    { id: 'tec_statement', required: true }, { id: 'commercial_eval', required: true },
    { id: 'comparative_statement', required: true }, { id: 'price_justification', required: true }
  ],
  pnc_rec: [{ id: 'pnc_agenda', required: true }],
  pp: [
    { id: 'tec_statement', required: true }, { id: 'commercial_eval', required: true },
    { id: 'comparative_statement', required: true }, { id: 'price_justification', required: true },
    { id: 'pnc_recommendation', required: false }, { id: 'advance_payment', required: false }
  ],
  po: [{ id: 'purchase_proposal', required: true }],
  po_amendment: [{ id: 'purchase_order', required: true }, { id: 'hal_contract', required: true }],
  advance_payment: [{ id: 'advance_payment', required: true }]
};

// Block 1 of the sheet — the pre-tender input checklist, each line owned by one agency.
export const CHECKLIST = [
  {
    group: 'PROVISIONING NOTE',
    items: [
      { label: 'Indentor Checklist (Tender No. from IFS)', owner: 'Indenting' },
      { label: 'MPR/CAR/SPR/CPR — descp, part no, qty, delivery period, type of tendering', owner: 'Indenting' },
      { label: 'Technical Specs', owner: 'Indenting' },
      { label: 'Scope of Work', owner: 'Indenting' },
      { label: 'Proprietary / OEM Service Certificate', owner: 'Indenting' },
      { label: 'Single Tender / Nomination Certificate', owner: 'Indenting' },
      { label: 'Commercial Conditions', owner: 'Tendering' }
    ]
  },
  {
    group: 'FORMATS (FOR INDENT)',
    items: [
      { label: 'MII — Make in India purchase preference', owner: 'Tendering' },
      { label: 'LBS — land border sharing restriction (GFR 144(ix))', owner: 'Tendering' },
      { label: 'Non-poaching undertaking', owner: 'Tendering' },
      { label: 'Non-debarring undertaking', owner: 'Tendering' },
      { label: 'NDA', owner: 'Tendering' },
      { label: 'IP — Integrity Pact', owner: 'Tendering' },
      { label: 'SD — Security Deposit BG format', owner: 'Tendering' },
      { label: 'PBG — Performance BG format', owner: 'Tendering' }
    ]
  },
  {
    group: 'IFS REFERENCE',
    items: [{ label: 'IFS Tender Enquiry No. — against Requisition No.', owner: 'Tendering' }]
  }
];

export const optionAt = (nodeId, noteId) =>
  (CASCADE_NODES[nodeId]?.options ?? []).find((o) => o.noteId === noteId) ?? null;

export const otherAgency = (a) => (a === 'Indenting' ? 'Tendering' : 'Indenting');

export default {
  AGENCIES, START, SHORT_CLOSURE_MESSAGE, STAGE_META, CASCADE_NODES, POST_TENDER_FORMATS,
  FORMAT_OWNER, FORMAT_TITLE, PREREQ_FORMATS, CHECKLIST, optionAt, otherAgency
};
